name: Android Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          flutter build apk
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter drive --driver=test_driver/main_test.dart --target integration_test/app_test.dart

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: Screenshot
          path: screenshots/*.png
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
